version: "3.9"

services:
  backend:
    build:
      context: ./computer_alerts-be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/computeralerts

  frontend:
    build:
      context: ./computer_alerts-fe
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  mongo:
    image: mongo:6.0
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  mongodb_data:
