# src/main/resources/application.yml
frontend:
  url: http://localhost:3000

backend:
  url: http://localhost:8080

website:
  domain: localhost



spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/computeralerts
      database: computeralerts

server:
  port: 8080 # Default port for Spring Boot




auth0:
    clientId: dErtDK4v3hzp0FoM26aX9qGDayGobMIs
    clientSecret: "hzlT0vFjt6RvkYIT9Y5mZcB6Vl_vAA3McVxf_2yMsmI4E074pQqbGn3G4ZpTxMXI"
    domain: dev-im24qkb6l7t2yhha.ca.auth0.com
    audience: https://dev-im24qkb6l7t2yhha.ca.auth0.com/api/v2/
