# Common Configuration
frontend:
  #  url: http://localhost:3000
  url: {your frontend domain} # place here
cloudinary:
  url: {Cloudinary URL provided}

backend:
  url: http://localhost:8080

website:
  domain: localhost

spring:
  data:
    mongodb:
      #      host: mongo
      #      port: 27017
      uri: ${MONGO_CONNECTION_STRING}
      database: {Database name}
      auto-index-creation: true

server:
  port: 8080

  error:
    include-message: always

logging:
  level:
    root: INFO
    com.calerts: DEBUG

auth0:
  clientId: {Add Auth0 ClientId}
  clientSecret: {Add Auth0 Secret}
  domain: {Add Auth0 Domain}
  audience: {Add Auth0 Audience}

---
# Test Configuration
spring:
  config:
    activate:
      on-profile: test

  data:
    mongodb:
      username: root
      password: password
      host: localhost
      port: 0
      database: {enter database name}
      authentication-database: admin
      auto-index-creation: true

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 5.0.5

auth0:
  clientId: test-client-id
  clientSecret: test-client-secret
  domain: test-domain
  audience: test-audience